<?php

namespace Test\AbraFlexi\Mailer;

use AbraFlexi\Mailer\Mailer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-10-14 at 14:18:43.
 */
class MailerTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Mailer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Mailer();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Mailer\Mailer::templateFile
     * @todo   Implement testtemplateFile().
     */
    public function testtemplateFile() {
        $this->assertEquals('', $this->object->templateFile());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Mailer\Mailer::addItem
     * @todo   Implement testaddItem().
     */
    public function testaddItem() {
        $this->assertEquals('', $this->object->addItem());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Mailer\Mailer::getCss
     * @todo   Implement testgetCss().
     */
    public function testgetCss() {
        $this->assertEquals('', $this->object->getCss());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Mailer\Mailer::getCurrentMailSize
     * @todo   Implement testgetCurrentMailSize().
     */
    public function testgetCurrentMailSize() {
        $this->assertEquals('', $this->object->getCurrentMailSize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Mailer\Mailer::addInvoice
     * @todo   Implement testaddInvoice().
     */
    public function testaddInvoice() {
        $this->assertEquals('', $this->object->addInvoice());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Mailer\Mailer::addCompanyLogo
     * @todo   Implement testaddCompanyLogo().
     */
    public function testaddCompanyLogo() {
        $this->assertEquals('', $this->object->addCompanyLogo());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Mailer\Mailer::addQrCode
     * @todo   Implement testaddQrCode().
     */
    public function testaddQrCode() {
        $this->assertEquals('', $this->object->addQrCode());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Mailer\Mailer::addAttachments
     * @todo   Implement testaddAttachments().
     */
    public function testaddAttachments() {
        $this->assertEquals('', $this->object->addAttachments());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Mailer\Mailer::send
     * @todo   Implement testsend().
     */
    public function testsend() {
        $this->assertEquals('', $this->object->send());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
