<?php

declare(strict_types=1);

/**
 * This file is part of the AbraFlexi Mailer package
 *
 * https://github.com/VitexSoftware/abraflexi-mailer
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Mailer;

use AbraFlexi\Mailer\Templater;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-10-14 at 14:18:43.
 */
class TemplaterTest extends \PHPUnit\Framework\TestCase
{
    public \AbraFlexi\FakturaVydana $invoicer;
    protected Templater $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->invoicer = new \AbraFlexi\FakturaVydana();
        $this->invoicer->loadFromAbraFlexi($this->invoicer->getFirstRecordID());
        $helper = new \AbraFlexi\Mailer\Mailer($this->invoicer);
        $this->object = new Templater(
            $this->invoicer,
            'tests/test.ftl',
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Mailer\Templater::process
     */
    public function testprocess(): void
    {
        $this->assertEquals(
            \Ease\Shared::appName(),
            $this->object->process(file_get_contents($this->object->template)),
        );
    }

    /**
     * @covers \AbraFlexi\Mailer\Templater::variableBase
     */
    public function testvariableBase(): void
    {
        $this->assertEquals('', $this->object->variableBase(''));
    }

    /**
     * @covers \AbraFlexi\Mailer\Templater::variableProperty
     */
    public function testvariableProperty(): void
    {
        $this->assertEquals('', $this->object->variableProperty(''));
    }

    /**
     * @covers \AbraFlexi\Mailer\Templater::stripMarkup
     */
    public function teststripMarkup(): void
    {
        $this->assertEquals('', $this->object->stripMarkup(''));
    }
}
