<?php

namespace Test\AbraFlexi\Mailer;

use AbraFlexi\Mailer\Templater;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-10-14 at 14:18:43.
 */
class TemplaterTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Templater
     */
    protected $object;

    /**
     *
     * @var \AbraFlexi\FakturaVydana
     */
    public $invoicer;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->invoicer = new \AbraFlexi\FakturaVydana();
        $this->invoicer->loadFromAbraFlexi($this->invoicer->getFirstRecordID());
        $helper         = new \AbraFlexi\Mailer\Mailer($this->invoicer);
        $this->object   = new Templater(
            $this->invoicer,
            'tests/test.ftl'
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers AbraFlexi\Mailer\Templater::process
     */
    public function testprocess()
    {
        $this->assertEquals(
            \Ease\Shared::appName(),
            $this->object->process(file_get_contents($this->object->template))
        );
    }

    /**
     * @covers AbraFlexi\Mailer\Templater::variableBase
     */
    public function testvariableBase()
    {
        $this->assertEquals('', $this->object->variableBase(''));
    }

    /**
     * @covers AbraFlexi\Mailer\Templater::variableProperty
     */
    public function testvariableProperty()
    {
        $this->assertEquals('', $this->object->variableProperty(''));
    }

    /**
     * @covers AbraFlexi\Mailer\Templater::stripMarkup
     */
    public function teststripMarkup()
    {
        $this->assertEquals('', $this->object->stripMarkup(''));
    }
}
