.TH ABRAFLEXI-POTVRZENI-PRIJETI-FAKTURY 1 "2026" "abraflexi-mailer" "User Commands"
.SH NAME
abraflexi-potvrzeni-prijeti-faktury \- AbraFlexi Document Mailer component
.SH SYNOPSIS
.B abraflexi-potvrzeni-prijeti-faktury
.SH DESCRIPTION
.B abraflexi-potvrzeni-prijeti-faktury
is a component of the abraflexi-mailer package.
.SH AUTHOR
Vítězslav Dvořák <info@vitexsoftware.cz>
