.TH ABRAFLEXI-POTVRZENI-PRIJETI-UHRADY 1 "2026" "abraflexi-mailer" "User Commands"
.SH NAME
abraflexi-potvrzeni-prijeti-uhrady \- AbraFlexi Document Mailer component
.SH SYNOPSIS
.B abraflexi-potvrzeni-prijeti-uhrady
.SH DESCRIPTION
.B abraflexi-potvrzeni-prijeti-uhrady
is a component of the abraflexi-mailer package.
.SH AUTHOR
Vítězslav Dvořák <info@vitexsoftware.cz>
