.TH ABRAFLEXI-SEND-UNSENT-WITH-ATTACHMENTS 1 "2026" "abraflexi-mailer" "User Commands"
.SH NAME
abraflexi-send-unsent-with-attachments \- AbraFlexi Document Mailer component
.SH SYNOPSIS
.B abraflexi-send-unsent-with-attachments
.SH DESCRIPTION
.B abraflexi-send-unsent-with-attachments
is a component of the abraflexi-mailer package.
.SH AUTHOR
Vítězslav Dvořák <info@vitexsoftware.cz>
